### ISSUE TITLE
Nominate Xiao Zhang(@wawa0210) as Maintainers

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/community#55]
**Who you are going to nominate?**

- Name: Xiao Zhang
- GitHub ID: @wawa0210
- Affiliation: [DaoCloud](https://www.daocloud.io/)

**Why do we need more maintainers?**

Karmada joined the efforts with [500+ contributors](https://karmada.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1) from [60+ companies](https://karmada.devstats.cncf.io/d/5/companies-table?orgId=1) across [20+ countries](https://karmada.devstats.cncf.io/d/50/countries-statistics-in-repository-groups?var-period_name=5%20Years&var-countries=All&var-repogroup_name=All&var-metric=contributions&var-cum=countries), the above efforts take the community to [a new height](https://github.com/karmada-io/community/blob/main/cncf_process/incubation_dd/Karmada%20CNCF%20Due%20Diligence%20Doc.md#community-growth):
- The number of contributions increased to 1500+ per month
- The number of new PRs increased to 30+ per week
- The number of adopters increased to 20+. (See [Karmada Adopters](https://karmada.io/adopters) for the whole list)

We need more maintainers to help manage the contributions to ensure the project remains stable and grows fast.

**The reason why nominate him/she:**

@wawa0210 joined the community since year 2021 and [made significant contributions](https://github.com/pulls?q=author%3Awawa0210+user%3Akarmada-io+) to the community. Now he is leading the effort of the Karmada Commercial Support program. 

@wawa0210 is the leader of the container team at DaoCloud, over the last two years, he and his team made [significant contributions to the project](https://karmada.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1), and some of the team members are taking the [reviewer](https://github.com/karmada-io/community/blob/main/REVIEWERS.md)/[approver ](https://github.com/karmada-io/community/blob/main/APPROVERS.md) role to help the project stable, secure and up-to-date.

As a maintainer, @wawa0210 will help to manage contributions to the project, ensure project sustainability, and so on.

**Comment by wawa0210** [comment]
Thanks for the nomination @RainbowMango . 

DaoCloud started paying attention to the Karmada project in 2021, After extensive community research, Karmada was selected as the foundation for our multi-cloud  enterprise-grade solution [KairShip](https://docs.daocloud.io/kairship/01product/what/) . Team members have since then begun to make some community contributions within their capabilities(codes, document etc). Some results so far are shown below

- Incubate, lead and continue to maintain karmada-operator to make the installation and maintenance of karmada more reliable
- Continuously contribute to Karmadactl, scheduler, resourceinterpreter, metricsadapter and other core areas of karmada. And has multiple reviewers and maintainers in these fields.
- @samzong and @windsonsea they have contributed a total of 25+ PR to karmada-website
- Participated in many community activities and meetups to share Karmada production practices(Karmada meetup and Kubecon and etc)
- Continuously output multiple blogs to share Karmada usage experience(by Wechat Subscriptions), such as
  - 云原生多云应用利器--Karmada 总览篇
  - 云原生多云应用利器 -- Karmada 控制器
  - 云原生多云应用利器 -- Karmada 调度器
  - 云原生信仰者云集 | 一线云原生专家干货分享
  - Karmada 1.3 新特性：基于污点的故障迁移
  - Karmada 资源解释器
  - DaoCloud 结合 Karmada 打造新一代企业级多云平台
  - Karmada 差异化 GUI，简化跨集群应用配置
  - Karmada 资源传播详解
  - 更高效地实现故障转移
  - Karmada Failover 详解
  - Kamrada operator：新一代的 Karmada 管理方式

I myself also contributed 23+ PRs (minor code optimizations) to karmada [@wawa0210](https://github.com/karmada-io/karmada/pulls/wawa0210), my contributions are insignificant compared to those of my other colleagues. Many colleagues have become reviewers and approvers in the karmada community for their continued important contributions, such as @chaunceyjiang @calvin0327
@carlory  @samzong


If I am honored to be a Karmada maintainer, I will continue to promote my previous work (code contribution, community evangelism, publicity), and also focus on community governance, subgroup work, etc.

**Comment by RainbowMango** [comment]
As per [the community governance](https://github.com/karmada-io/community/blob/main/GOVERNANCE.md), invite all maintainers to vote here. 
/assign @carmark @GitHubxsy @kevin-wangzefeng @lfbear @mrlihanbo @zoroyouxi @RainbowMango

**Comment by RainbowMango** [comment]
+1
from me

**Comment by samzong** [comment]
/lgtm

Congratulations @wawa0210 ！

**Comment by kevin-wangzefeng** [comment]
+1 from me.
Thanks for all the work you have done, and welcome on board!
Looking forward to more of your contribution on the new role.

**Comment by RainbowMango** [comment]
Congrats! The vote passed!
I'll help to get @wawa0210 on board by updating the [Karmada Maintainers](https://github.com/karmada-io/karmada/blob/master/MAINTAINERS.md) list.

**Comment by wawa0210** [comment]
> +1 from me. Thanks @wawa0210 for all the work you have done, and welcome on board! Looking forward to more of your contribution on the new role.

It's a great honor and I will continue to make some contributions to the Karmada community

**Comment by RainbowMango** [comment]
/close
The membership has been updated.
